### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by michellemerrill**
Updating the README with Codespaces info -- **please do not merge this PR until we go LIVE on 2/17 at 8am PT**.

### CODE REVIEW

**Review by ameeraldraji — APPROVED** [review]
Hi

**Review by ameeraldraji — APPROVED** [review]
Hi

**Comment by PranamBhat** [comment]
Great going!

**Review by Mentukunge — APPROVED** [review]

**Review by JpSub7 — COMMENTED** [review]
3343256

**Comment by JpSub7** [comment]
#3378

**Comment by JpSub7** [comment]
#3343256

**Comment by FrancescoRomeo02** [comment]
some one know how fix an error of -e option?

**Review by JpSub7 — COMMENTED** [review]
J}ornpierags.83@gmail.com;} jp83@outlook.de 

[_NaN;jpsb7_inkmsingnight(denied edservice.) / /:/off#61234565 _

**Pull request merged**
