### PR TITLE
Update readme icon for education

### PR DESCRIPTION
**Pull request by ettaboyle**
Updating the icon for education from a book to the backpack (satchel)

### CODE REVIEW

**Review by Apple1D — COMMENTED** [review]
- [ ] Ok

**Review by Apple1D — COMMENTED** [review]
- [ ]

**Comment by Vsnimo89** [comment]
> * [ ] موافق

**Comment by rizwankunigal-ai** [comment]
Rizwank@gmail.com

**Review by rizwankunigal-ai — COMMENTED** [review]
RIZWANK 
-wved2p

**Pull request merged**
