### PR TITLE
https://github.com/vCreate SECURITY.md

### PR DESCRIPTION
**Pull request by KatyWinslet**
Valen.toast.

### CODE REVIEW

**Review by Piyaphartoi — COMMENTED** [review]
KatyWinslet:patch-1

**Comment by Rudolfino67** [comment]
Request

**Comment by Rudolfino67** [comment]
485fcb3

**Review by Dong1999heo — COMMENTED** [review]
#16960

**Comment by organicghemp** [comment]
bien

**Review by feaaaan — COMMENTED** [review]
Quiero aprender mucho

**Comment by entoncescomo1001** [comment]
https://pbs.twimg.com/profile_images/1371299388228825098/ZNmC62.jpg

**Pull request closed without merging**
