### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by queenofcorgis**
Removing sentence that links to a 404 page

### CODE REVIEW

**Review by amantank — COMMENTED** [review]
LGTM

**Comment by gallegosdamian505** [comment]
...

**Review by gallegosdamian505 — COMMENTED** [review]
...

**Review by justinmchase — COMMENTED** [review]
I would change this:

> You don't need to have a solution to the problem you are facing to kick off a discussion.

to

> You don't need to have a solution for the problem you are facing in order to kick off a discussion.

The double use of the word "to" makes the sentence a little awkward.

**Review by gallegosdamian505 — COMMENTED** [review]
...

**Review by jricciardi — APPROVED** [review]

**Pull request merged**
