### PR TITLE
Update links to Docs site in CoC

### PR DESCRIPTION
**Pull request by samus-aran**

### CODE REVIEW

**Review by queenofcorgis — APPROVED** [review]

**Review by ettaboyle — APPROVED** [review]

**Review by vsoto37 — COMMENTED** [review]
https://github.com/community/community/pull/78986#issuecomment-1854148408

**Comment by Jaiprakash26** [comment]
Thanks 😊

**Review by CosmicJesterX — COMMENTED** [review]
pls approve

**Review by CosmicJesterX — COMMENTED** [review]
lease review

**Pull request merged**
