### PR TITLE
docs(governance): coc v2.1

### PR DESCRIPTION
**Pull request by suitupstan**
Adds contributor convent coc v2.1

### CODE REVIEW

**Review by Eliraze — COMMENTED** [review]
[]()

**Review by EllioTTDawson — COMMENTED** [review]
> [CODE_OF_CONDUCT.md]()

**Comment by moh449** [comment]
> Adds contributor convent coc v2.1

gjgh

**Comment by dhztao68** [comment]
Okay. CHANGE

**Comment by dhztao68** [comment]
Okay

**Comment by raffihart** [comment]
Please shoot me mining procedure thanks in advance

**Comment by alexcnichols** [comment]
:wave: Hey @krishguptadev - Thanks for visiting our feedback discussions repository. Doing a version rev on our Code of Conduct isn't something I want to pick up just yet. We have some exciting plans for next year, which would be better timing to do something like this and rollout to our moderators, contributors, and visitors. We're still early in our journey though with this repository so I'll keep this in mind. Closing for now.

**Comment by Eliraze** [comment]
recover

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
