### PR TITLE
Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by michellemerrill**
updating CoC links

### CODE REVIEW

**Review by tony710521 — COMMENTED** [review]
謝謝

**Comment by Hotmen1** [comment]
michellemerrill-patch-3

**Comment by 0344666610** [comment]
https://binance-docs.github.io/apidocs/futures/en/#event-order-update

**Comment by 0344666610** [comment]
@0344666610

**Comment by 0344666610** [comment]
Answers enabled

**Comment by 0344666610** [comment]
gh pr checkout 25245

**Review by 0344666610 — COMMENTED** [review]
http://CODE_OF_CONDUCT.md

**Comment by 0344666610** [comment]
CODE_OF_CONDUCT.md

**Pull request merged**
