### PR TITLE
Add some missing commas in the README

### PR DESCRIPTION
**Pull request by adamlawson22**
This makes the README easier to read and is grammatically correct.

### CODE REVIEW

**Review by michellemerrill — APPROVED** [review]

**Comment by bdr2486** [comment]
> This makes the README easier to read and is grammatically correct.

**Review by bdr2486 — COMMENTED** [review]
README.md

**Comment by nenaqui** [comment]
https://github.com/community/community/pull/4662#issuecomment-897095783

**Comment by nenaqui** [comment]
https://github.com/community/community/pull/4662#issuecomment-897095783

**Pull request merged**
