### PR TITLE
Create main.yml

### PR DESCRIPTION
**Pull request by stefanQ83**

### CODE REVIEW

**Comment by danifreudstein** [comment]
What would you like to talk about? I’m very open to discussing anything really. I don’t care about what we discuss, just go ahead and discuss something. Thanks

**Comment by farezdaniel13** [comment]
can you teach me how i want use this apps

**Comment by danifreudstein** [comment]
It’s crap, I would bother with it. Delete it off your phone. I don’t know what the stupid app is about either. It’s all computer tech garbage that no one really needs to know, except for people that don’t have a life. So don’t be like these people, get a life be happy and buy that dream home with the white picket fence, God dam it! 
ihack into stuff all the time but I don’t need idiots to tell me how to do it so they look important. Their the most boring unimportant people on here. It’s crap 💩

**Comment by feaaaan** [comment]
?me interesa  bastante  aprender todo

**Comment by feaaaan** [comment]
Estupendo

**Comment by feaaaan** [comment]
Necesito más información

**Comment by Stylelee8** [comment]
> 

It’s me joe

**Comment by Joeridevits** [comment]
I can not understand

**Pull request closed without merging**
