### PR TITLE
Change icon Pull request

### PR DESCRIPTION
**Pull request by packetspoofer**

### CODE REVIEW

**Comment by Loremente** [comment]
🛢it's more cute

**Comment by tazimamatovzeka** [comment]
Let's go

**Review by itsmeshibintmz — COMMENTED** [review]
Looks better.

**Comment by kelvinsoonk0** [comment]
commeit with me

**Comment by nogran** [comment]
i like it

**Review by packetspoofer — COMMENTED** [review]
Merge pull request

**Review by itsmeshibintmz — COMMENTED** [review]
👍

**Comment by Loremente** [comment]
@itsmeshibintmz you can merge it?

**Comment by itsmeshibintmz** [comment]
Nah, I don't have the permission.

**Pull request closed without merging**
