### PR TITLE
Create SECURITY.me

### PR DESCRIPTION
**Pull request by 1720498**

### CODE REVIEW

**Review by java4119 — COMMENTED** [review]
https://github.com/community/community/discussions/29814
https://docs.github.com/en/education/contribute-with-github-community-exchange/getting-started-with-github-community-exchange

**Review by David21101991 — COMMENTED** [review]
>

**Review by 0746106363 — COMMENTED** [review]
#31393

**Comment by Arezoomohammadalizadeh** [comment]
> > 

thankyou🙏

**Comment by NicoletteChez** [comment]
Thanks.  I'll look into it.

**Comment by onixpunki** [comment]
>

**Comment by Emmy888** [comment]
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=feedback-id:message-id:date:subject:cc:to:from:mime-version
         :dkim-signature:dkim-signature;
        bh=xJsDXpf7m/in6gjiAS+gjcehP6b+ZoF0GDp8aYO9qHk=;
        b=TF3q8nP+LDU6S5YaDZN5BY9yfjQEd4vPHjgZaazH62hYeqTKFe96JsT+BQRrHX/fOt
         olkgx/aAN3THfLeChHFAOBBMs7Uc6eYzEwJzU76Sr2+bRza/HXq3CP40XbCHYhQRYVK7
         +3OF4nYPFDsSe8Y8LFcCfYYTgAt5CWD1wAy6YdRKYb9oZQ5SbjXUeFfwwi7Y6Z/6Xxo2
         6W6Pe+6UMqJ+EQanTPYcqzfZKYQPk4QT2r1rXTYqJLmuzpGxLx2sUh5ufNgZyrxzhKL+
         IhsMPw9LCPr1YBMROUTtVbNN81gcMbIx47sABkkl5G140ZKEMFYwyT2vILF9c7ICsktW
         QlMw==

**Review by MUHAMMADFMP — COMMENTED** [review]
Now

**Comment by raipidddd0ex** [comment]
https://bit.ly/3ANhhUr

**Pull request closed without merging**
