### PR TITLE
Create Wichian

### PR DESCRIPTION
**Pull request by khawpan1996**
..

### CODE REVIEW

**Review by skaille — COMMENTED** [review]
#

**Comment by skaille** [comment]
#28663

**Comment by drhrdr** [comment]
@khawpan1996

**Comment by drhrdr** [comment]
#28663 @khawpan1996

**Review by drhrdr — COMMENTED** [review]
Create Wichian #28663 @skaille 

> ``Create Wichian #28663 # @khawpan1996

**Comment by drhrdr** [comment]
ttps://github.com/absolute-version/absolute-version-js/actions/workflows/build-and-test.yml/badge.svg?branch=main&event=workflow_run)](https @khawpan1996 

- [ ] 

- [ ] o

**Comment by tyntyn1** [comment]
@khawpan1996

**Review by tyntyn1 — COMMENTED** [review]
@khawpan1996 @bancavui @davidstaheli @drhrdr @zackfern

**Comment by hasaniasm** [comment]
> ..

Yes

**Review by Sanggai — COMMENTED** [review]
Use alt + click/return to exclude labels
or ⇧ + click/return for logical OR

**Pull request closed without merging**
