### PR TITLE
404 -> Github webhook doc link

### PR DESCRIPTION
**Pull request by lx78WyY0J5**
update https://docs.github.com/en/developers/webhooks-and-events/webhooks/about-webhook to https://docs.github.com/en/developers/webhooks-and-events/webhooks/about-webhooks

just added an "s"

### CODE REVIEW

**Review by lx78WyY0J5 — COMMENTED** [review]
Style not dead, 🔗 work again, i can read this doc 👍 ❤️

**Comment by attractiveDev** [comment]
Hello, Nice to meet you.

**Comment by lx78WyY0J5** [comment]
> 

Hi, nice to meet you, .... can i help you maybe ?

**Comment by www62070** [comment]
> update https://docs.github.com/en/developers/webhooks-and-events/webhooks/about-webhook to https://docs.github.com/en/developers/webhooks-and-events/webhooks/about-webhooks
> 
> just added an "s"

**Comment by lx78WyY0J5** [comment]
Please do not answer to this poste for no reason
This is just a PR for docs... not a chat room for saying "Hi" or empty message 😢

**Pull request closed without merging**
