### PR TITLE
Automatically add a comment to feedback and bug reports with a thank you message

### PR DESCRIPTION
**Pull request by mgriffin**
We should have an automated way to reply to people that open up feedback discussions or bug reports in the community forum. This PR will add that as a GitHub Action that's triggered on a labeling event.

### CODE REVIEW

**Comment by danfod1** [comment]
I thanks the community

**Comment by danfod1** [comment]
Nice community

**Review by jricciardi — APPROVED** [review]
LGTM

**Comment by Indr1102** [comment]
IMG-20240610-WA0066

**Comment by Sa-su121** [comment]
[@Sa-su121's untitled project - Backlog.tsv.csv](https://github.com/user-attachments/files/15904414/%40Sa-su121.s.untitled.project.-.Backlog.tsv.csv)

**Review by DannygreyT — COMMENTED** [review]
here you go

**Review by DannygreyT — COMMENTED** [review]
here you go

**Comment by synasapmob** [comment]
this PR is good i think so

**Comment by DannygreyT** [comment]
All us well

**Comment by DannygreyT** [comment]
All us well

**Comment by Jakk626** [comment]
Is it immoral to ask if it's possible to learn hacking from the tech wizards on here? I have no tech knowledge but have been playing about with GBT's and have got some decent results. Being disabled, I can't leave the house so I'm at the computer all day, if I were to learn how to hack there's lots of employment for those. And of course, disclaimer, Anything learned or information given to help me will be used in a clean enviornment and NEVER for bad acting. I'm trying to learn red team hacking as I think I'd enjoy that more. Hopefully someone can help or point me in the correct direction

**Comment by Jakk626** [comment]
I don't get it, I've never used GitHub before.

**Comment by Nichebiche** [comment]
Jakk626 I'm on the same page you are. Email me and we can learn together christielaw33@yahoo.com I'm a disabled mother of 4 and if I could make an income I could crate a better life for me and my 4 children.

**Pull request merged**
