### PR TITLE
Update CoC to version 2.0

### PR DESCRIPTION
**Pull request by Tyler887**
This updates the Contributor Covenant code of conduct to version 2.0 from the early 1.4.

### CODE REVIEW

**Comment by Sadboipoor** [comment]
c6ab39906d236e874fbcfe2f5303e83cd7260d7e

**Comment by PopeTongue** [comment]
> [c6ab399](https://github.com/github/feedback/commit/c6ab39906d236e874fbcfe2f5303e83cd7260d7e)

Cheer up Buck

**Review by davidcruz8642 — COMMENTED** [review]
Manage your business with an all-in-one platform

**Comment by 0963166991** [comment]
https://www.facebook.com/profile.php?id=100040677634079
It's hacked. Can you save me? I do not have an email address. Can you help me?

**Comment by 0963166991** [comment]
It's hacked. Can you save me? I do not have an email address. Can you help me?

**Comment by Tyler887** [comment]
> ~~Manage your business with an all-in-one platform~~

Don't spam using reviews! Spam is not permitted anywhere on GitHub. "CoC" means "code of conduct".

All of these comments are **spam**!

**Comment by michellemerrill** [comment]
We will be reviewing the CoC and providing any needed updates, in the near future.

**Pull request closed without merging**
