### PR TITLE
docs: fix link in readme

### PR DESCRIPTION
**Pull request by rethab**

### CODE REVIEW

**Comment by Arezoomohammadalizadeh** [comment]
دریافت Outlook برای iOS<https://aka.ms/o0ukef>
________________________________
فرستنده: rethab ***@***.***>
‏‏ارسال شده: Wednesday, September 28, 2022 11:39:54 AM
گیرنده: community/community ***@***.***>
گیرنده کپی: Subscribed ***@***.***>
‏‏موضوع: [community/community] docs: fix link in readme (PR #34424)

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/community/community/pull/34424

Commit Summary

  *   14ca841<https://github.com/community/community/pull/34424/commits/14ca8412cf93b982020e09a5713c571570b43487> docs: fix link in readme

File Changes

(1 file<https://github.com/community/community/pull/34424/files>)

  *   M README.md<https://github.com/community/community/pull/34424/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5> (2)

Patch Links:

  *   https://github.com/community/community/pull/34424.patch
  *   https://github.com/community/community/pull/34424.diff

**Review by Mk1206mk — COMMENTED** [review]
rethab:patch-1

**Comment by davidjoshuashelton** [comment]
rethab:patch-1

**Review by alanjacobmathew — COMMENTED** [review]
Fixes #32693

**Pull request closed without merging**
