### PR TITLE
Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by ghostinhershell**
Added "Reasonable use of AI generated content" section to the Community Code of Conduct

### CODE REVIEW

**Comment by jirawat97224** [comment]
J

**Comment by jirawat97224** [comment]
> J

**Review by jirawat97224 — COMMENTED** [review]
J

**Comment by jirawat97224** [comment]
J

**Review by mojtabaahmadi1367 — COMMENTED** [review]
Delat

**Comment by dismosoul999** [comment]
# GitHub CLI api
# https://cli.github.com/manual/gh_api

gh api \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /orgs/ORG/codespaces- uses: actions/checkout@v2-beta
  with:
    ref: ${{ github.event.pull_request.head.sha }}//Reading data
using (var fileStream = File.OpenRead("c:\temp\data.txt"))
{
    var flatfile = new FlatFile<TestObject>(layout, fileStream);
    foreach(var objectInstance in flatfile.Read())
    {
        //Do Somethig....
    }
}

//Writing data
using (var fileStream = File.OpenWrite("c:\temp\data.txt"))
{
    var flatfile = new FlatFile<TestObject>(layout, fileStream)
    flatfile.Write(listOfObjects);
}LICENSE- uses: actions/checkout@v2-beta
  with:
    repository: myAccount/myRepository
    ref: refs/heads/master
    token: ${{ secrets.GitHub_PAT }} # `GitHub_PAT` is a secret that contains your PAT

**Review by dismosoul999 — COMMENTED** [review]
https://www.jadaktech.com/products/machine-vision/var layout = new Layout<TestObject>.DelimitedLayout()
	            .WithDelimiter(";")
	            .WithQuote("\"")
				.HeaderLines(1)
	            .WithMember(o => o.Id, set => set.WithLength(5).WithLeftPadding('0'))
	            .WithMember(o => o.Description, set => set.WithLength(25).WithRightPadding(' '))
	            .WithMember(o => o.NullableInt, set => set.WithLength(5).AllowNull("=Null").WithLeftPadding('0'))
                .WithMember(o => o.NullableEnum, set => set.WithLength(10).AllowNull("").WithLeftPadding(' '))
                .WithMember(o => o.Date, set => set.WithFormat(new CultureInfo("pt-PT")));- uses: actions/checkout@v2-beta
  with:
    ref: ${{ github.event.pull_request.head.sha }}- uses: actions/checkout@v2-beta
  with:
    ref: some-branchsteps:
    - uses: actions/javascript-action@main  # do not do this- uses: actions/checkout@v2-beta
  with:
    repository: myAccount/myRepository
    ref: refs/heads/master
    token: ${{ secrets.GitHub_PAT }} # `GitHub_PAT` is a secret that contains your PATCould complete computer  software  work in
JohannabrozinMichaelLöfvenhaft organizations.org
0704758414
content/account-and-profile/setting-up-and-managing-your-github-profilecontent/account-and-profile/setting-up-and-managing-your-github-profile528262530704758414https://github.com/kemitchell/funding-schema.json/issues/9#issue-2054730231https://terabox.com/wap/activity/recipient2?code=f_5823013580701697_4398376978711&pid=aGoldTaskgh repo clone github/docsdismosoulCONTRIBUTING.michaelLöfvenhaft ifanypart2CONTRIBUTINGdismosouldismosoulwww.GitHub.Bissness_inoutsoulision@live.orgHttp://www.GitHub.Bissness_inoutsoulision@live.orghttps://play.google.com/store/apps/details?id=de.twokit.castbrowser🇬🇵🇬🇵🇬🇵🇬🇵911a9d7a-4ea5-472d-8bb0-bab774334d02Request Id: 911a9d7a-4ea5-472d-8bb0-bab774334d02
Correlation Id: 0a7daf5f-1698-401e-af58-ebb40e5daa40
Timestamp: 2023-12-20T04:45:52Z
Message: AADSTS50020: User account 'michaellofvenhaft2@gmail.com' from identity provider 'live.com' does not exist in tenant '' and cannot access the application '4813382a-8fa7-425e-ab75-3b753aab3abb'(Microsoft Authenticator App) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.<!-- Error while uploading openkeychain_log.txt -->@michaelione @jamdon . org live word be loerirealocdowm up lo key open nosoluiortion riplocsolica oshen saliosen be pron
Bemeciclocaso miriodrdrasiaklipp on this banloclsholocloadlacolanotihobino dowloseingsajsonjson be happii i tkinksou hi blievlodrasizopfar rip yor fil dowlode ner installet toöla tools zipfil ace![1000069867.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/71258445-7442-444c-a593-78ee79a63ae5)

![1000069800.png](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/1db74407-627a-428e-98bd-49ac9d40b8c5)

![1000069904.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/d8443bfc-f186-47a7-91a3-3be92c0da7ee)

![1000069865.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/e8127b7a-f08a-483f-8690-9ca08404004b)

![1000069905.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/5ff69044-80a6-4eea-9621-d4708d5194a6)

![1000069795.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/46fc98b8-61af-4d6f-994c-d7676a772def)

![1000069803.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/846c7171-d94e-4b05-aa09-80c961834ac8)

![1000069864.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/47c05e14-c4cf-4e1e-b7fc-20bc20c4cfe1)

[]()<!-- Error while uploading 100004<!-- Error while uploading 1000047933.jpg -->3.jpg …]()

<!-- Error while uploading 1000048358.jpg --><!-- Error while uploading 1000037<!-- Error while uploading 100004<!-- Error while uploading 1000048356.jpg -->ng 1000048356.jpg …]()

![1000047931.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/59325890-c5c7-48ae-ac44-<!-- Error while uploading 1000048359.jpg -->ploading 1000048352.jpg <!-- Error while uploading 100004<!-- Error while uplo<!-- Error while uploading 1000048351.jpg -->…]()

![Uploading 1000048353.jpg …]()

![Uploading 100004<!-- Error while uploading 1000048355.jpg -->ploading 1000048350.jpg -->![Uploadi<!-- Error while uploading 1000048347.jpg<!-- Error while uploading 1000047930.jpg -->Error while uploa<!-- Error while uploading 1000039887.heic -->g 1000039887.heic …]()

![Uplo<!-- Error while uploading 1000048345.jpg -->ploading 1000048343.jpg -->3.jpg …]()

![Uploading 100004<!-- Error while uploading 1000048342.jpg -->8344.jpg …]()

![Uploading 1000048342.jpg …]()

![Uploading 100004834<!--<!-- Error while uploading 1000048293.jpg -->0048297.jpg -->ic -->.heic …]()

<!-- Error while uploading 1000048298.jpg -->![Uploading 1000048297.jpg …]()

![Uploading 1000048293.jpg …]()

![Uploading 100004<!-- Error while uploading 1000039863.heic -->138.jpg …]()

![Uploading 1000039863<!-- Error while uploading 1000048284.jpg -->4.jpg …]()

![Uploadi<!-- Error while uploading 1000037284.heic -->g <!-- Error while uploading 1000043256.jpg -->le uploading 1000039833.heic -->

![Uploading 1000039833.heic …]()

![Uploadi<!-- Error while uploading 1000<!-- Error while uploading 1000039831.heic -->]()

![Uploading 1000043256.jpg …]()

![Uploading 1000039831.heic …]()

![1000036962.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/asset<!-- Error while uploading 1000048312.jpg -->7a-4a2<!-- Error while uploading 1000046098.jpg -->8<!-- Error while uploading 1000048310.jpg -->.jpg …]()

![1000046097.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/280b56cf-4456-4ead-808f-abfe3249dcbd)

![Uploading 1000048310.jpg …]()

<!-- Error while uploading 1000048277.jpg -->![1000046092.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/102a1a4e-bd20-4125-910a-54f777c500f8)

<!-- Error while uploading 1000039<!-- Error while uploading 1000048276.jpg -->6.jpg …]()

<!-- Error while uploading 1000039828.heic![1000036956.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/3fa1a2d4-01c4-4d27-9a5a-44fe388e7e3f)

00039<!-- Error while uploading 100003<!-- Error while uploading 1000048274.jpg -->ng 1000048274.jpg …]()

<!-- Error while uploading 1000046096.jpg -->![1000046095.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/bc37b729-507b-40c4-bdeb-e3a4f395dec0)

![Uploading 1000036956.jpg …]()

![1000046093.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/bff0a386-d211-4551-8bf2-7bb1da7776cb<!-- Error while uploading 1000046122.jpg -->)

![Uploading 1000046122.jpg …]()

![1000046086.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/c3e25462-d690-4da3-acf1-227c93ccbed3<!-- Error while uploading 1000046121.jpg -->)

![Uploadi<!-- Error while uploading 1000046088.jpg -->ng 1000046088.jpg …]()

<!-- Error while uploading 1000047934.jpg --><!-- Error while uploading 1000046081.jpg --><!-- Error while uploading 1000046085.jpg -->![Uploading 1000037237<!-- Error while uploading 1000046082.jpg -->2.jpg …]()

![Uploading 1000037238.heic …]()

![Uploading 1000037074.heic …]()

<!-- Error while uploading 1000037072.jpg --><!-- Error while uploading 1000046080.jpg --><!-- Error while uploading 1000046084.jpg --><!-- Error while uploading 1000046111.jpg --><!-- Error while uploading 1000046078.jpg --><!-- Error while uploading 1000046077.jpg --><!-- Error while uploading 1000048376.jpg --><!-- Error while uploading 1000048375.jpg --><!-- Error while uploading 1000048372.jpg --><!-- Error while uploading 1000048373.jpg --><!-- Error while uploading 1000037236.heic -->![1000048371.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/8ee371d8-a2cd-4eae-8fa4-a49faa5c19e2)

![1000037085.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/1d1f1e4b-ca10-490a-9a98-037b4c7aa0bc)

<!-- Error while uploading 1000037080.jpg --><!-- Error while uploa<!-- Error while uploading 1000046064.jpg -->ploading 1000046100.j<!-- Error while uploading 100004<!-- Error while uploading 1000046074.jpg -->1000048368.j<!-- Error while uplo<!-- Error while uploading 100004<!-- Error while uploading 1000046103.jpg --><!-- Erro<!-- Error while uplo<!-- Error while uploading 1000046069.jpg -->ading 1000048369.jpg …]()

![Uploading 100004836<!-- Error while uploading 100004<!-- Error while uplo<!-- Error while uploading 1000046110.jpg -->8363.jpg …]()

![Uploading 1000048365.jpg …]()

<!-- Error while uplo<!-- Error while uploading 1000046061.mp4 -->loading 1000048360.jpg …]()

![Uploading 1000046063.jpg …]()

![Uploading 1000046110.jpg …]()

![Uploading 1000048362.jpg …]()

Uploading 1000046061.mp4 …

 Port folg login keyloss vi wellvgo on with mioss life togaderi lif go on losonson bilatlokesion rip yorip thetbilocogolalopaesia la pho lobshit yu givbos noew lorieckey laesson locit upno du låse up mit lås nu annasrsa banrip gig anrs du kommer ongrara dig tri mig gosse lodlocorizip tools fil yoervdow lod ner lipzip falielenbfilen du länka ihop dem två sakernerna tillsammans ått oss du det vibsäger till dig du ska göra det nu.🤑🤑🤔🤔🤔🤫🤫💃💃🙃🎅🤶⛷⛷🧙🧙🧙⛷⛷# - - [ ] ~~<!-- Error while uploading 1000048166.mp4 -->![1000062854.jpg](https://github.com/JSCRIPT300-Spring2015/Module_![1000062866.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/042320f7-b0b1-4bff-a2ca-a0fc7bae0f18)

4f60-9e1e-35b980e01952)

![1000062851.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/53e91e3e-db01-4711-a7e8-b8db1d73f877)

![Uploading 1000062866.jpg …]()

![1000068139.png](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/a110302e-879c-4f06-8d68-92f089a37f3a)

<!-- Error while uploading 1000055168.mp4 -->![1000059084.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/b38bd8a1-913c-432b-8e31-8d8d82f7bd79)

https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/2831d8e5-fb10-469f-8f5b-45a666ba89b2

![1000046059.png](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/173e8e42-2971-4c70-a5b8-616ca614d01e)

<!-- Error while uploading 1000055167.mp4 --><!-- Error while uploading 1000047939.mp4 --><!-- Error while uploading 1000055166.mp4 -->![1000059058.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/7cd7f8a9-4f24-4ef9-a8f4-90b485ed8f66)

![1000062848.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/3636de2b-3d29-48b0-bd9d-32c162dd4bcc)

![1000062849.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022![1000062853.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/d7f041df-5441-4a75-90a1-9eb7812d5c08)

7.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/cc92e505-7bf3-4e5d-923f-1aa2ec9ea2e2)

e uploading 1000048050.mp4 --><!-- Error while uploading 1000047989.mp4 -->![Uploading 1000062847.jpg …]()

<!-- Error while uploading 1000047994.mp4 -->Uploading 1<!-- Error while uploading 1<!-- Error while uploading 1000048164.mp4 -->p4 …

Uploading 1000048164.mp4 …

![1000055127.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/7c3babf5-8fb4-46ad-bd7<!-- Error <!-- Error while uploading 1000047992.mp4 -->p4 -->000048165.mp4 …

Uploading 1000047992.mp4 …

![Uploading 1000062853.jpg![1000055243.png](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/d8fd0b14-b1de-4788-9b6f-3ce3c29fa26c)



https://github.com/JSCRIPT300-Spring2015/Module_5/asse<!-- Error while uploading 1000047985.mp4 -->80e-a9d6-06cb7ea59d9f

Uploading 1000047985.mp4 …

![Uploading 1000055243.png …]()

![1000062850.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/f6eef2e3-024e-4a<!-- Error while uploading 1000047984.mp4 -->Error while uploading 1000055120.png -->Uploading 1000047984.mp4 …

![1000069800.png](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/f882fdd3-2861-4e37-8fba-8e7587efe0ce)

![1000062859.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/edfe689c-1572-418d-8c42-9a6937303158)

![1000062857.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/![1000046097.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/5936633a-a05c-4a1a-9874-6b2b3bf74908)

-f3705d58dfa7)

<!-- Error while uploading 1000048154.mp4 -->![Uploading 1000046097.jpg …]()

<!-- Error while uploading 1000048396.mp4 --<!-- Error while uploading 1000048392.mp4 -->ithub.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/c645edad-64de-4890-81ae-ff4ee13d1c94)

<!-- Error while uploading 1000048150.mp4 -->Uploading 1000048392.mp4 …

<!-- Error while uploading 1000048157.mp4 -->![1000046092.jpg](https://github.com/JSCRIPT300-Spring2015/Module_<!-- Error while uploading 1000048394.mp4 -->8a52-4af2-b4b2-28d7d5f07489)

![Uploading 1000<!-- Error while uploading 1000048032.mp4 -->000048032.mp4 …

Uploading 1000048394.mp4 …

Uploading 100004803![1000062868.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/6757309a-eb7e-4aa5-a3c8-c127d84d5611)

pg …]()

![1000048395.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/99aea<!-- Error while uploading 1000055116.jpg -->
![Uploading 1000055116.jpg …]()

![1000062865.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/b4cc12b6-88b3-4e9c-bf49-ff362b071687)

![Upload![1000062860.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/dbe4ac67-cdee-4368-b726-2738f479a5e<!-- Error while uploading 1000048390.jpg -->loading 1000048390.jpg …]()

![Uploading 1000062860.jpg …]()

![Uploading 1000062868.jpg …]()

![1000062861.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/ab52963d-f<!-- Error while uploading 1000047965.mp4 -->
Uploading 1000047965.mp4 …

![1000055072.png](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/7f798c69-c889-480f-909b-27689084b093)

![Uploading 1000055070.jpg …]()![1000062867.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/92d1d153-8dd0-454f-a674-137a2aa5c9a5)

oading 1000048397.mp4 …

![1000055071.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/8257409a-bbfd-4767-901e-f5a483d2f70b)

![Uploading 1000062867.jpg …]()<!-- Error while uploading 1000048265.mp4 -->![1000048381.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/371818e9-eefd-4b01-818c-1474a798785a)



<!-- Error while uploading 1000048387.mp4 -->Uploading 1000048265.mp4 …

![Uploading 1000048381.jpg …]()

999<!-- Error while uploading 1000048142.mp4 --><!-- Error while uploading 1000048141.mp4 --><!-- Error while uploading 1000048262.mp4 -->77709<!-- Error while uploading 1000055107.png -->![Uplo<!-- Error while uploading 1000048129.mp4 -->ploading 1000048384.mp4 …

<!-- Error while uploading 1000055108.jpg --><!-- Error while uplo<!-- Error while uploading 1000047956.mp4 -->ading 1000047956.mp4 …

![1000055069.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/2b98a40e-cc24-42ce-84d1-b9219bc19ef9)

Uploading 100004<!-- Error while uploading 1000069794.jpg --><!-- Erro<!-- Error while uploading 1000048379.jpg -->-->8.jpg …]()

![Uploading 1000048379.jpg …]()

https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/12b97c86-41d7-4855-836e-98529d8344de

7<!-- Error while uploading 1000048253.mp4 -->Uploading 100004<!-- Error while uploading 1000048002.mp4 -->7955.mp4 …

<!-- Error while uploading 1<!-- Error while uploading 1000055171.mp4 -->000055171.mp4 …

<!-- Error while uploading 1000055170.mp4 --><!-- Error while uploading 1000047945.mp4 -->2<!-- Error while uploading 1000048247.webm -->Uploading 1000048002.mp4 …

971![1000046064.jpg](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/2ab05dbb-11d4-44eb-a932-73d2d4986211)

![1000046062.png](https://github.com/JSCRIPT300-Spring2015/Module_5/assets/145758022/75c3a0aa-c4ee-4396-8306-dedfa8acad41)

<!-- Error while uploading 1000048402.jpg --><!-- Error while uploading 1000048401.jpg -->9<!-- Error while uploading 1000055169.mp4 -->375<!-- Error while uploading 1000048248.webm -->8rip lod lol in yoe shipped foriorteripfolocofoulsoul safar🎅🎅🎅🎅⛷💃💃🤫🤔🤑🤑😏🧛‍♂️🧛‍♂️🙃🙃@michaelione @jamdon 😘😇😇😉🙃🙃😉🙂🙂🙂🤑🤑🤫🤔🤨😬😲😕😕😕☹☹☹👻👻👻👻👻👻👻👻👻👻🤖🤖🤖👾👾👾👾🤖🤖🤖👻👻👻🙊🙉🙈💌❤❤❤🖤💜💙💚💛🧡💜💙💜💜💜💯💢💢💢💜❣❣~~lokeylupnoloperdier locup me no ouiloerasion bi commer soun be snart på när a

**Review by dismosoul999 — COMMENTED** [review]
# GitHub CLI api
# https://cli.github.com/manual/gh_api

gh api \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /orgs/ORG/codespaces

**Review by Lo236816 — COMMENTED** [review]
### ****

**Comment by Lo236816** [comment]
Reverting changes

**Review by Tobie1992 — COMMENTED** [review]
Rtrr

**Comment by jshcstd2000-afk** [comment]
https://github.com/yekto/Sweet-Bonanza-Slot-Hack-Free-Spin-Hack.github

**Pull request closed without merging**
