### PR TITLE
Delete LICENSE-CODE

### PR DESCRIPTION
**Pull request by mmm2499**

### CODE REVIEW

**Comment by mmm2499** [comment]
...

**Comment by graymundo032** [comment]
> ...

**Comment by MemeHoovy** [comment]
https://user-images.githubusercontent.com/97995998/198900601-73a6caa5-e825-47ea-9c23-5df393f40107.mp4

**Comment by MemeHoovy** [comment]
> gh pr checkout 36269

You are such a dumbass

**Comment by MemeHoovy** [comment]
> #18051

Shut the fuck up

**Comment by MemeHoovy** [comment]
> mmm2499:patch-1 Duplicate of #

Kindly fuck off

**Pull request closed without merging**
