### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by michellemerrill**
Adding category finder in table view to the readme

### CODE REVIEW

**Comment by natalierjackson** [comment]
lgtm 🚀

**Comment by natalierjackson** [comment]
🚀

**Review by willsmythe — APPROVED** [review]

**Review by natalierjackson — APPROVED** [review]
🚀

**Review by vinicioviquez — COMMENTED** [review]
Seattle Colleges are nothing but a bunch of liars and white collar thieves. Ask me as I can proof of what im talking about with real evidence.

**Comment by GoaGill** [comment]
> Adding category finder in table view to the readme

**Pull request merged**
