### PR TITLE
Further relax README now that General is out

### PR DESCRIPTION
**Pull request by chadwhitacre**
Follow-up to 4ead69d4b1f84c827e1ee0a6f8a16f13aa830d51 ... presuming that "General" is a catch-all for any product/feature.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
P.S. Arrived here [from Twitter](https://twitter.com/alexcnichols/status/1402356262700941317), cc: @alexcnichols.

**Review by michellemerrill — APPROVED** [review]
Adding additional clarification re: general category

**Comment by michellemerrill** [comment]
Thanks @chadwhitacre for your suggestions!  Appreciate you taking the time to flesh out the README 🌟

**Comment by chadwhitacre** [comment]
For the record, it looks like this was closed in favor of 1a19f1f03a9377aebbc97528d3ea2803958e49e6.

**Comment by michellemerrill** [comment]
@chadwhitacre I've just been in the habit of editing the README it directly since it's pretty lightweight, but thank you again for your review, as I incorporated many of your suggestions!

**Pull request closed without merging**
